// Generated by gencpp from file servicelea/personResponse.msg
// DO NOT EDIT!


#ifndef SERVICELEA_MESSAGE_PERSONRESPONSE_H
#define SERVICELEA_MESSAGE_PERSONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace servicelea
{
template <class ContainerAllocator>
struct personResponse_
{
  typedef personResponse_<ContainerAllocator> Type;

  personResponse_()
    : result()  {
    }
  personResponse_(const ContainerAllocator& _alloc)
    : result(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::servicelea::personResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::servicelea::personResponse_<ContainerAllocator> const> ConstPtr;

}; // struct personResponse_

typedef ::servicelea::personResponse_<std::allocator<void> > personResponse;

typedef boost::shared_ptr< ::servicelea::personResponse > personResponsePtr;
typedef boost::shared_ptr< ::servicelea::personResponse const> personResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::servicelea::personResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::servicelea::personResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::servicelea::personResponse_<ContainerAllocator1> & lhs, const ::servicelea::personResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::servicelea::personResponse_<ContainerAllocator1> & lhs, const ::servicelea::personResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace servicelea

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::servicelea::personResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::servicelea::personResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::servicelea::personResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::servicelea::personResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::servicelea::personResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::servicelea::personResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::servicelea::personResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c22f2a1ed8654a0b365f1bb3f7ff2c0f";
  }

  static const char* value(const ::servicelea::personResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc22f2a1ed8654a0bULL;
  static const uint64_t static_value2 = 0x365f1bb3f7ff2c0fULL;
};

template<class ContainerAllocator>
struct DataType< ::servicelea::personResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "servicelea/personResponse";
  }

  static const char* value(const ::servicelea::personResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::servicelea::personResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string result\n"
;
  }

  static const char* value(const ::servicelea::personResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::servicelea::personResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct personResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::servicelea::personResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::servicelea::personResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "result: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVICELEA_MESSAGE_PERSONRESPONSE_H
