// Generated by gencpp from file servicelea/person.msg
// DO NOT EDIT!


#ifndef SERVICELEA_MESSAGE_PERSON_H
#define SERVICELEA_MESSAGE_PERSON_H

#include <ros/service_traits.h>


#include <servicelea/personRequest.h>
#include <servicelea/personResponse.h>


namespace servicelea
{

struct person
{

typedef personRequest Request;
typedef personResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct person
} // namespace servicelea


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::servicelea::person > {
  static const char* value()
  {
    return "c198113e7dd9cc5c9fd5f271c8479b39";
  }

  static const char* value(const ::servicelea::person&) { return value(); }
};

template<>
struct DataType< ::servicelea::person > {
  static const char* value()
  {
    return "servicelea/person";
  }

  static const char* value(const ::servicelea::person&) { return value(); }
};


// service_traits::MD5Sum< ::servicelea::personRequest> should match
// service_traits::MD5Sum< ::servicelea::person >
template<>
struct MD5Sum< ::servicelea::personRequest>
{
  static const char* value()
  {
    return MD5Sum< ::servicelea::person >::value();
  }
  static const char* value(const ::servicelea::personRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::servicelea::personRequest> should match
// service_traits::DataType< ::servicelea::person >
template<>
struct DataType< ::servicelea::personRequest>
{
  static const char* value()
  {
    return DataType< ::servicelea::person >::value();
  }
  static const char* value(const ::servicelea::personRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::servicelea::personResponse> should match
// service_traits::MD5Sum< ::servicelea::person >
template<>
struct MD5Sum< ::servicelea::personResponse>
{
  static const char* value()
  {
    return MD5Sum< ::servicelea::person >::value();
  }
  static const char* value(const ::servicelea::personResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::servicelea::personResponse> should match
// service_traits::DataType< ::servicelea::person >
template<>
struct DataType< ::servicelea::personResponse>
{
  static const char* value()
  {
    return DataType< ::servicelea::person >::value();
  }
  static const char* value(const ::servicelea::personResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVICELEA_MESSAGE_PERSON_H
